# RCC Conda Configuration for Data Science
# Uses uv for fast package installation
# https://github.com/joshyorko/rcc

channels:
  - conda-forge

dependencies:
  - python=3.12.11
  - uv=0.9.28

  # Data science packages from conda (better binary support)
  - pandas=2.2.3
  - numpy=2.1.3
  - scikit-learn=1.5.2
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - jupyter=1.1.1

  - pip:
      - joblib==1.4.2
      - openpyxl==3.1.5
