# Sema4ai Actions package.yaml (v2 spec)
# For use with action-server
# https://github.com/joshyorko/actions

spec-version: v2

name: my-actions
description: Custom AI actions and MCP tools

dependencies:
  conda-forge:
    - python=3.12.10
    - uv=0.6.11
  pypi:
    - sema4ai-actions=1.3.15
    - sema4ai-mcp=0.0.1
    - requests>=2.32.0
    - pydantic>=2.0.0

pythonpath:
  - src
  - tests

dev-dependencies:
  pypi:
    - pytest=8.3.3
    - black=24.10.0
    - ruff=0.8.0

dev-tasks:
  test: pytest tests -v
  format: black src tests
  lint: ruff check src
  typecheck: pyright src

packaging:
  exclude:
    - ./.git/**
    - ./output/**
    - ./**/__pycache__
    - ./.venv/**
    - ./tests/**
    - ./*.md
