endpoints:
  cloud-api: https://api.eu1.robocorp.com/
  cloud-linking: https://cloud.robocorp.com/link/
  cloud-ui: https://cloud.robocorp.com/
  downloads: https://cdn.sema4.ai/
  docs: https://sema4.ai/docs/
  telemetry: https://sema4.ai/api/telemetry
  issues: https://telemetry.robocorp.com/

diagnostics-hosts:
  - files.pythonhosted.org
  - github.com
  - conda.anaconda.org
  - pypi.org

autoupdates:
  templates: https://cdn.sema4.ai/templates/templates.yaml

certificates:
  verify-ssl: true
  ssl-no-revoke: false
  legacy-renegotiation-allowed: false

options:
  no-build: false

network:
  no-proxy: # no no proxy by default
  https-proxy: # no proxy by default
  http-proxy: # no proxy by default

meta:
  name: default
  description: Sema4.ai default settings.yaml internal to rcc
  source: builtin
  version: 2024.06
