# RCC Conda Configuration for Work Items
# Producer-Consumer pattern with robocorp.tasks
# https://github.com/joshyorko/rcc

channels:
  - conda-forge

dependencies:
  - python=3.12.11
  - uv=0.9.28
  - pip:
      # Core automation
      - robocorp==3.0.0
      - robocorp-workitems==1.4.5
      - robocorp-truststore==0.9.1

      # Custom adapters (choose one or more)
      # - robocorp-adapters-custom  # SQLite, Redis, DocumentDB

      # Common utilities
      - requests==2.32.5
      - pydantic==2.10.0
